name: Demo CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "LICENSE"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "LICENSE"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Use Node.js 18
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm test
  docker_build:
    name: Build the production docker image
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4.1.7
      - run: docker build . -t greenict/demo-api
